name: Build for NewABI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Cache Theos
        uses: actions/cache@main
        with:
          path: theos
          key: theos
      - name: Checkout roothide/theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: roothide/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout theos/sdks
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          sparse-checkout: |
            iPhoneOS16.5.sdk
            iPhoneOS15.6.sdk
            iPhoneOS14.5.sdk
          path: theos/sdks
      - name: Install Build Dependencies
        run: |
          brew install make xz ldid
      - name: Add Roothide to Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"
      - name: Build Package
        run: |
          export THEOS=theos
          gmake clean package FINALPACKAGE=1
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=roothide

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: packages/*.deb