name: macOS Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Cache Theos
        id: cache-theos
        uses: actions/cache@main
        with:
          path: theos
          key: theos
      - name: Checkout theos/theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
      - name: Checkout opa334/AltList
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: opa334/AltList
          ref: main
          path: AltList
      - name: Checkout theos/sdks
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          sparse-checkout: |
            iPhoneOS16.5.sdk
            iPhoneOS15.6.sdk
            iPhoneOS14.5.sdk
          path: theos/sdks
      - name: Install Build Dependencies
        run: |
          brew install make xz ldid
      - name: Install AltList
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=../theos
          cd AltList
          ./install_to_theos.sh
          cd ..
      - name: Copy AltList Headers
        if: steps.cache-theos.outputs.cache-hit != 'true'
        run: |
          export THEOS=theos
          mkdir -p $THEOS/include/AltList
          cp ./AltList/*.h $THEOS/include/AltList
      - name: Build Package
        run: |
          export THEOS=theos  
          gmake clean package FINALPACKAGE=1
          gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: packages/*.deb