name: Build for NewABI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      - name: Cache Theos
        uses: actions/cache@main
        with:
          path: theos
          key: theos
      - name: Cache AltList
        uses: actions/cache@main
        with:
            path: altlist
            key: altlist
      - name: Checkout theos/theos
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos
      - name: Checkout opa334/AltList
        if: steps.cache-altlist.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: opa334/AltList
          ref: main
          path: altlist
      - name: Checkout theos/sdks
        if: steps.cache-theos.outputs.cache-hit != 'true'
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          sparse-checkout: |
            iPhoneOS16.5.sdk
            iPhoneOS14.5.sdk
          path: theos/sdks
      - name: Install Build Dependencies
        run: |
          brew install make xz ldid
      - name: Install AltList
        run: |
          (export THEOS=~/theos && cd altlist && ./install_to_theos.sh)
      - name: Build Package
        run: |
          export THEOS=~/theos
          gmake clean package FINALPACKAGE=1

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          path: packages/*.deb